name:            peg-coffee
version:         0.0.0
description:     A PEG parser.
license:         WTFPL
repository:
  type:          git
  url:           http://github.com/connec/peg-coffee.git
devDependencies:
  chai:          ^4.1.2
  coffeescript:  ^2.1.0
  mocha:         ^4.0.1
  plantation:    0.0.17
  sinon:         ^4.1.3
  sinon-chai:    ^2.14.0
  yaml-js:       0.2.2
