name:        peg-cs
version:     0.0.0-pre
description: A PEG parser.
license:     WTFPL
repository:
  type: git
  url:  http://github.com/connec/peg-cs.git
devDependencies:
  coffee-script: ~1.3.0
  chai:          ~1.2.0
  mocha:         ~1.4.0