name:            peg-coffee
version:         0.0.0
description:     A PEG parser.
license:         WTFPL
repository:
  type:          git
  url:           http://github.com/connec/peg-coffee.git
devDependencies:
  coffee-script: ~1.9
  plantation:    0.0.15